"""Add lockout fields

Revision ID: 481039a32713
Revises: cd598c0cad46
Create Date: 2026-02-24 21:39:16.600086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481039a32713'
down_revision: Union[str, Sequence[str], None] = 'cd598c0cad46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'local'"))
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'failed_attempts')
    # ### end Alembic commands ###
